name: Main
on:
  push: 
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use check-out
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version:"21.2"
      - name: instalacja dependecji
        run: npm install
      - name: Testowanie
        run: npm test
deploy: 
  runs_on: ubuntu_latest
  needs: [build]
  steps:
    - name: Krok 1
      uses: actions/checkout@v4
    - name: Krok 2
      uses: azure/appservice-build@v3
      with:
        platform: nodejs
        version: 21.2.0
    - name:
      uses: azure/webapps-deploy@v1
      with:
        app-name: node112675
        publish-profile: ${{secrets.AZURE_WEB_PROFILE}}
